wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
beam_size:
  value: 2
dec_dim:
  value: 256
dec_embedding_dim:
  value: 128
dropout_rate:
  value: 0.6
enc_dim:
  value: 64
enc_embedding_dim:
  value: 128
learning_rate:
  value: 0.0008999518979251972
linear_dim:
  value: 1024
model:
  value: lstm
momentum:
  value: 0.964964875920484
n_decoders:
  value: 4
n_encoders:
  value: 4
optimizer:
  value: rmsprop
