wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 1024
beam_size:
  value: 1
dec_dim:
  value: 512
dec_embedding_dim:
  value: 64
dropout_rate:
  value: 0.6
enc_dim:
  value: 256
enc_embedding_dim:
  value: 128
learning_rate:
  value: 0.008785691224789624
linear_dim:
  value: 64
momentum:
  value: 0.8993231423967317
n_decoders:
  value: 1
n_encoders:
  value: 1
optimizer:
  value: adamw
use_attn:
  value: true
