_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.7
            "8":
                - 2
                - 5
            "12": 0.19.7
            "13": darwin-x86_64
activation:
    value: gelu
batch_size:
    value: 256
beam_size:
    value: 2
dec_dim:
    value: 256
dec_embedding_dim:
    value: 128
dropout_rate:
    value: 0.4
enc_dim:
    value: 512
enc_embedding_dim:
    value: 64
epochs:
    value: 20
learning_rate:
    value: 0.0009841113814454806
linear_dim:
    value: 1024
log_connectivity:
    value: false
model:
    value: gru
momentum:
    value: 0.9181842286762628
n_decoders:
    value: 4
n_encoders:
    value: 3
native:
    value: hi
optimizer:
    value: adamw
sweep_id:
    value: null
use_attn:
    value: false
use_test:
    value: false
use_v2:
    value: false
wandb:
    value: false
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: da6401-assignment3
wandb_sweep:
    value: true
