_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 16
                - 17
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.7
            "8":
                - 2
                - 5
            "12": 0.19.7
            "13": darwin-x86_64
activation:
    value: tanh
batch_size:
    value: 128
beam_size:
    value: 2
dec_dim:
    value: 512
dec_embedding_dim:
    value: 64
dropout_rate:
    value: 0.2
enc_dim:
    value: 512
enc_embedding_dim:
    value: 512
epochs:
    value: 20
learning_rate:
    value: 0.0008679588865292194
linear_dim:
    value: 128
log_connectivity:
    value: false
model:
    value: lstm
momentum:
    value: 0.9390345827949242
n_decoders:
    value: 4
n_encoders:
    value: 4
native:
    value: hi
optimizer:
    value: adam
sweep_id:
    value: null
use_attn:
    value: false
use_test:
    value: true
use_v2:
    value: false
wandb:
    value: true
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: da6401-assignment3
wandb_sweep:
    value: false
